version: '3.8'
services:
  app:
    image: auth-local
    build: .
    command: start-local
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/healthcheck || exit 1" ]
      interval: "30"
      retries: "3"
      start_period: "60"
    env_file: .env
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_REPLICA_HOST: db
    ports:
      - 3000:${PORT}
    networks:
      standardnotes_proxy:
        aliases:
          - auth
      auth: {}
    volumes:
      - .:/var/www

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    expose:
      - 3306
    ports:
      - 32789:3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - auth

  cache:
    image: redis:6.0-alpine
    volumes:
      - ./data/redis/:/data
    expose:
      - 6379
    ports:
      - 6380:6379
    networks:
      - auth

networks:
  auth:
    name: auth
  standardnotes_proxy:
    name: standardnotes
